<?php

/**
 * @file
 * Pull a JSON file from Ungerboeck containing ServSafe events, and display the events in a block.
 */


/**
 * Implements hook_block_info().
 */
function ungerboeck_servsafe_block_info() {
  // Create the right appropriate number of blocks
  $blocks['ungerboeck_servsafe'] = array(
    'info' => t('Ungerboeck - ServSafe Events'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function ungerboeck_servsafe_block_configure($delta = "") {
  $form = array();
  if (drupal_substr($delta, 0, 19) === 'ungerboeck_servsafe') {
    $settings = variable_get($delta . '_block', ungerboeck_servsafe_defaults());

    $form[$delta] = array(
      '#type' => 'fieldset',
      '#collaspible' => TRUE,
      '#collasped' => TRUE,
    );

    $form[$delta][$delta . '_orgcode'] = array(
      '#type' => 'textfield',
      '#title' => t('OrgCode'),
      '#description' => t('For ISU, this is usually 10'),
      '#size' => 15,
      '#default_value' => $settings['orgcode'],
    );

    $form[$delta][$delta . '_search'] = array(
      '#type' => 'textfield',
      '#title' => t('Search String'),
      '#description' => t('This is the OData search string. Note: #TodayDate# will be replaced by the actual date'),
      '#size' => 175,
      '#maxlength' => 300,
      '#default_value' => $settings['search'],
    );
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function ungerboeck_servsafe_block_save($delta = '', $edit = array()) {
  if (drupal_substr($delta, 0, 19) === 'ungerboeck_servsafe') {
    $settings['orgcode'] = $edit[$delta . '_orgcode'];
    $settings['search'] = $edit[$delta . '_search'];

    variable_set($delta . '_block',  $settings);
  }
}


/**
 * Implements hook_block_view().
 */
function ungerboeck_servsafe_block_view($delta = '') {
  $token = ungerboeck_helpers_get_token();
  $blocksettings = variable_get($delta . '_block', ungerboeck_servsafe_defaults());

  $event_list = ungerboeck_helpers_get_event_list($blocksettings['orgcode'], $blocksettings['search'], $token);
  $json_events = json_decode(strip_tags($event_list), TRUE);

  $results = '<ul class="ungerboeck_servsafe">';

  foreach ($json_events as $event) {
    $time = strtotime($event['StartDate']);
    $location = str_replace(', IA', '', $event['Description']);
    $location = str_replace('SERVSAFE (Spanish) - ', '', $location);
    $location = str_replace('SERVSAFE - ', '', $location);
    $webaddress = $event['WebAddress'];

    if ($event['WebAddress'] == '') {
      $event_details = json_decode(strip_tags(ungerboeck_helpers_get_event_details($blocksettings['orgcode'], $event['EventID'], $token)), TRUE);
      $webaddress = $event_details['EventUserFieldSets'][0]['UserText01'];
    }

    $results .= '<li>';
    $results .= '<a href="' . $webaddress . '">' . $location;
    if (strpos($event['Description'], 'Spanish') != FALSE) {
      $results .= ' (Spanish)';
    }

    $results .= '</a><br/>';
    $results .= date('l, F j, Y', $time) . '<br/>';

    $results .= '</li>';
  }

  $results .= '</ul>';

  $block['content'] = $results;

  return $block;
}

/**
 * Return the default settings for each block
 */
function ungerboeck_servsafe_defaults() {
  return array(
    'orgcode' => 10,
    'search' => 'Account eq \'00000150\' and Status eq \'30\' and StartDate ge DateTime\'#TodayDate#\'$orderby=StartDate,StartTime$page_size=4',
  );
}

