<?php

/**
 * @file
 * Pull a JSON file from Ungerboeck, and display the events in a block.
 */


/**
 * Implements hook_menu().
 */
function ungerboeck_helpers_menu() {
  $items['admin/config/content/ungerboeck_helpers'] = array(
    'title' => 'Ungerboeck Helpers Settings',
    'description' => 'Helper functions for Ungerboeck modules',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ungerboeck_helpers_settings'),
    'access arguments' => array('administer ungerboeck helpers'),
    'file' => 'ungerboeck_helpers.admin.inc',
  );

  return $items;
}


/**
 * Get the login token to access the API
 */
function ungerboeck_helpers_get_token() {
  $server_URL = variable_get('ungerboeck_helpers_server', 'https://registration.extension.iastate.edu');
  $username = variable_get('ungerboeck_helpers_username', 'rubiapiuser');
  $password = trim(decrypt(variable_get('ungerboeck_helpers_password', '')));

  // Fetch the page
  $curl_handle = curl_init();
  curl_setopt($curl_handle, CURLOPT_URL, $server_URL . '/api/v1/sdk_initialize');
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, array('Authorization: Basic ' . base64_encode($username . ':' . $password)));
  //curl_setopt($curl_handle, CURLOPT_HEADER, 1);
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl_handle, CURLOPT_CONNECTTIMEOUT, 1);
  $buffer = curl_exec($curl_handle);
  curl_close($curl_handle);

  return $buffer;
}

/**
 * Get today's date in yyyy-mm-dd format.
 */
function ungerboeck_helpers_get_todays_date() {
  return date('Y-m-d');
}

/**
 * Do substitutions to fix the search string to match what Ungerboeck wants.
 */
function ungerboeck_helpers_fix_search_string($search_string) {
  $search_string = str_replace('#TodayDate#', ungerboeck_helpers_get_todays_date(), $search_string);
  $search_string = str_replace(' ', '%20', $search_string);
  $search_string = str_replace('$', '%24', $search_string);
  $search_string = str_replace('=', '%3D', $search_string);


  return $search_string;
}


/**
 * Get a list of events using the API.
 */
function ungerboeck_helpers_get_event_list($orgcode, $search_string, $token) {
  $server_URL = variable_get('ungerboeck_helpers_server', 'https://registration.extension.iastate.edu');
  $search_URL = $server_URL . '/api/v1/Events/' . $orgcode . '?search=' . ungerboeck_helpers_fix_search_string($search_string);
  $token = trim(str_replace('"', '', $token));

  // Fetch the page
  $curl_handle = curl_init();
  curl_setopt($curl_handle, CURLOPT_URL, $search_URL);
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, array('token: ' . $token));
  //curl_setopt($curl_handle, CURLOPT_HEADER, 1);
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl_handle, CURLOPT_CONNECTTIMEOUT, 1);
  $buffer = curl_exec($curl_handle);
  curl_close($curl_handle);

  return $buffer;
}


/**
 * Get details of an event.
 */
function ungerboeck_helpers_get_event_details($orgcode, $eventID, $token) {
  $server_URL = variable_get('ungerboeck_helpers_server', 'https://registration.extension.iastate.edu');
  $search_URL = $server_URL . '/api/v1/Events/' . $orgcode . '/' . $eventID;
  $token = trim(str_replace('"', '', $token));

  // Fetch the page
  $curl_handle = curl_init();
  curl_setopt($curl_handle, CURLOPT_URL, $search_URL);
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, array('token: ' . $token));
  //curl_setopt($curl_handle, CURLOPT_HEADER, 1);
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl_handle, CURLOPT_CONNECTTIMEOUT, 1);
  $buffer = curl_exec($curl_handle);
  curl_close($curl_handle);

  return $buffer;
}

/**
 * Combine Date and Time into one variable.
 */
function ungerboeck_helpers_combine_date_time($StartDate, $StartTime) {
  $location_date = strpos($StartDate, 'T');
  $location_time = strpos($StartTime, 'T');

  return substr($StartDate, 0, $location_date) . substr($StartTime, $location_time);
}
