<?php

/**
 * @file
 * Contains ungerboeck_helpers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\encrypt\Entity\EncryptionProfile;

/**
 * Implements hook_help().
 */
function ungerboeck_helpers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ungerboeck_helpers module.
    case 'help.page.ungerboeck_helpers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Includes functions that could be used by multiple Ungerboeck modules') . '</p>';
      return $output;

    default:
  }
}


/**
 * Get the login token to access the API
 */
function ungerboeck_helpers_get_token() {
  $config = \Drupal::config('ungerboeck_helpers.settings');

  $encryption_profile = EncryptionProfile::load('ungerboeck');
  $server_URL = $config->get('server_url');
  $username = $config->get('username');
  $password = \Drupal::service('encryption')->decrypt($config->get('password'), $encryption_profile);

  // Fetch the page
  $curl_handle = curl_init();
  curl_setopt($curl_handle, CURLOPT_URL, $server_URL . '/api/v1/sdk_initialize');
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, array('Authorization: Basic ' . base64_encode($username . ':' . $password)));
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl_handle, CURLOPT_CONNECTTIMEOUT, 1);
  $buffer = curl_exec($curl_handle);
  curl_close($curl_handle);

  return $buffer;
}


/**
 * Get today's date in yyyy-mm-dd format.
 */
function ungerboeck_helpers_get_todays_date() {
  return date('Y-m-d');
}


/**
 * Do substitutions to fix the search string to match what Ungerboeck wants.
 */
function ungerboeck_helpers_fix_search_string($search_string) {
  $search_string = str_replace('#TodayDate#', ungerboeck_helpers_get_todays_date(), $search_string);
  $search_string = str_replace(' ', '%20', $search_string);
  $search_string = str_replace('$', '%24', $search_string);
  $search_string = str_replace('=', '%3D', $search_string);


  return $search_string;
}


/**
 * Get a list of events using the API.
 */
function ungerboeck_helpers_get_event_list($orgcode, $search_string, $token) {
  $config = \Drupal::config('ungerboeck_helpers.settings');

  $server_URL = $config->get('server_url');
  $search_URL = $server_URL . '/api/v1/Events/' . $orgcode . '?search=' . ungerboeck_helpers_fix_search_string($search_string);
  $token = trim(str_replace('"', '', $token));

  // Fetch the page
  $curl_handle = curl_init();
  curl_setopt($curl_handle, CURLOPT_URL, $search_URL);
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, array('token: ' . $token));
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl_handle, CURLOPT_CONNECTTIMEOUT, 1);
  //curl_setopt($curl_handle, CURLOPT_HEADER, 1);

  $buffer = curl_exec($curl_handle);
  curl_close($curl_handle);

  return $buffer;
}
