<?php

/**
 * @file
 * Contains ungerboeck_eventlist.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ungerboeck_eventlist($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ungerboeck_eventlist module.
    case 'help.page.ungerboeck_eventlist':
      $output = '';
      //$output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pulls a list of events from Ungerboeck, and display them in a block') . '</p>';
      $output .= '<p>&nbsp;</p>';
      return $output;

    default:
  }
}

/* 
 * Combine separate date and time variables into one variable
 */
function ungerboeck_eventlist_combine_date_time($datepart, $timepart) {
  return strtotime(date('m/d/y', strtotime($datepart)) . ' ' . date('H:i', strtotime($timepart)));
}
